// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type ActivityEvent struct {
	ID        string       `json:"id"`
	Type      ActivityType `json:"type"`
	User      *User        `json:"user"`
	Message   string       `json:"message"`
	Data      *string      `json:"data,omitempty"`
	Timestamp time.Time    `json:"timestamp"`
}

type AnalyticsSummary struct {
	UploadTrends  []*UploadTrend   `json:"uploadTrends"`
	UserActivity  []*UserActivity  `json:"userActivity"`
	FileTypeStats []*FileTypeStats `json:"fileTypeStats"`
	SharingStats  *SharingStats    `json:"sharingStats"`
	StorageStats  *StorageStats    `json:"storageStats"`
}

type AuditLog struct {
	ID           string    `json:"id"`
	User         *User     `json:"user,omitempty"`
	Action       string    `json:"action"`
	ResourceType string    `json:"resourceType"`
	ResourceID   string    `json:"resourceId"`
	Details      *string   `json:"details,omitempty"`
	CreatedAt    time.Time `json:"createdAt"`
}

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type CreateFolderInput struct {
	Name     string  `json:"name"`
	ParentID *string `json:"parentId,omitempty"`
	IsPublic *bool   `json:"isPublic,omitempty"`
}

type CreateUserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
}

type File struct {
	ID            string    `json:"id"`
	Name          string    `json:"name"`
	ContentHash   string    `json:"contentHash"`
	MimeType      string    `json:"mimeType"`
	Size          int       `json:"size"`
	Owner         *User     `json:"owner"`
	Folder        *Folder   `json:"folder,omitempty"`
	IsPublic      bool      `json:"isPublic"`
	DownloadCount int       `json:"downloadCount"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
	Tags          []*Tag    `json:"tags"`
}

type FileFilter struct {
	Filename *string    `json:"filename,omitempty"`
	MimeType *string    `json:"mimeType,omitempty"`
	MinSize  *int       `json:"minSize,omitempty"`
	MaxSize  *int       `json:"maxSize,omitempty"`
	FromDate *time.Time `json:"fromDate,omitempty"`
	ToDate   *time.Time `json:"toDate,omitempty"`
	Tags     []string   `json:"tags,omitempty"`
	Uploader *string    `json:"uploader,omitempty"`
}

type FileShare struct {
	ID        string    `json:"id"`
	File      *File     `json:"file"`
	User      *User     `json:"user"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type FileTypeStats struct {
	MimeType   string  `json:"mimeType"`
	Count      int     `json:"count"`
	TotalSize  int     `json:"totalSize"`
	Percentage float64 `json:"percentage"`
}

type Folder struct {
	ID         string    `json:"id"`
	Name       string    `json:"name"`
	Owner      *User     `json:"owner"`
	Parent     *Folder   `json:"parent,omitempty"`
	IsPublic   bool      `json:"isPublic"`
	Files      []*File   `json:"files"`
	Subfolders []*Folder `json:"subfolders"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type FolderShare struct {
	ID        string    `json:"id"`
	Folder    *Folder   `json:"folder"`
	User      *User     `json:"user"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Mutation struct {
}

type NotificationEvent struct {
	ID        string    `json:"id"`
	UserID    string    `json:"userId"`
	Type      string    `json:"type"`
	Title     string    `json:"title"`
	Message   string    `json:"message"`
	Data      *string   `json:"data,omitempty"`
	Timestamp time.Time `json:"timestamp"`
}

type Query struct {
}

type SharingStats struct {
	TotalShares       int       `json:"totalShares"`
	PublicFiles       int       `json:"publicFiles"`
	PublicFolders     int       `json:"publicFolders"`
	UserShares        int       `json:"userShares"`
	MostSharedFiles   []*File   `json:"mostSharedFiles"`
	MostSharedFolders []*Folder `json:"mostSharedFolders"`
}

type StorageStats struct {
	TotalStorage      int     `json:"totalStorage"`
	OriginalStorage   int     `json:"originalStorage"`
	SavedStorage      int     `json:"savedStorage"`
	SavingsPercentage float64 `json:"savingsPercentage"`
}

type Subscription struct {
}

type Tag struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Files     []*File   `json:"files"`
	CreatedAt time.Time `json:"createdAt"`
}

type UpdateFolderInput struct {
	Name     *string `json:"name,omitempty"`
	ParentID *string `json:"parentId,omitempty"`
	IsPublic *bool   `json:"isPublic,omitempty"`
}

type UpdateUserInput struct {
	Name         *string `json:"name,omitempty"`
	Password     *string `json:"password,omitempty"`
	StorageQuota *int    `json:"storageQuota,omitempty"`
	Role         *string `json:"role,omitempty"`
}

type UploadTrend struct {
	Date  string `json:"date"`
	Count int    `json:"count"`
	Size  int    `json:"size"`
}

type User struct {
	ID           string    `json:"id"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	Role         string    `json:"role"`
	StorageUsed  int       `json:"storageUsed"`
	StorageQuota int       `json:"storageQuota"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
	Files        []*File   `json:"files"`
	Folders      []*Folder `json:"folders"`
}

type UserActivity struct {
	UserID       string     `json:"userId"`
	UserName     string     `json:"userName"`
	UserEmail    string     `json:"userEmail"`
	FileCount    int        `json:"fileCount"`
	TotalSize    int        `json:"totalSize"`
	LastActivity *time.Time `json:"lastActivity,omitempty"`
	SharingCount int        `json:"sharingCount"`
}

type ActivityType string

const (
	ActivityTypeFileUploaded  ActivityType = "FILE_UPLOADED"
	ActivityTypeFileDeleted   ActivityType = "FILE_DELETED"
	ActivityTypeFolderCreated ActivityType = "FOLDER_CREATED"
	ActivityTypeFolderDeleted ActivityType = "FOLDER_DELETED"
	ActivityTypeFileShared    ActivityType = "FILE_SHARED"
	ActivityTypeFolderShared  ActivityType = "FOLDER_SHARED"
	ActivityTypeUserJoined    ActivityType = "USER_JOINED"
	ActivityTypeUserLeft      ActivityType = "USER_LEFT"
)

var AllActivityType = []ActivityType{
	ActivityTypeFileUploaded,
	ActivityTypeFileDeleted,
	ActivityTypeFolderCreated,
	ActivityTypeFolderDeleted,
	ActivityTypeFileShared,
	ActivityTypeFolderShared,
	ActivityTypeUserJoined,
	ActivityTypeUserLeft,
}

func (e ActivityType) IsValid() bool {
	switch e {
	case ActivityTypeFileUploaded, ActivityTypeFileDeleted, ActivityTypeFolderCreated, ActivityTypeFolderDeleted, ActivityTypeFileShared, ActivityTypeFolderShared, ActivityTypeUserJoined, ActivityTypeUserLeft:
		return true
	}
	return false
}

func (e ActivityType) String() string {
	return string(e)
}

func (e *ActivityType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ActivityType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ActivityType", str)
	}
	return nil
}

func (e ActivityType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ActivityType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ActivityType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
