package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.80

import (
	"context"
	"errors"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/BalkanID-University/vit-2026-capstone-internship-hiring-task-riyaautade/backend/internal/audit"
	"github.com/BalkanID-University/vit-2026-capstone-internship-hiring-task-riyaautade/backend/internal/auth"
	"github.com/BalkanID-University/vit-2026-capstone-internship-hiring-task-riyaautade/backend/internal/db"
	"github.com/BalkanID-University/vit-2026-capstone-internship-hiring-task-riyaautade/backend/internal/graph/generated"
	"github.com/BalkanID-University/vit-2026-capstone-internship-hiring-task-riyaautade/backend/internal/graph/model"
	"github.com/BalkanID-University/vit-2026-capstone-internship-hiring-task-riyaautade/backend/internal/realtime"
	"github.com/google/uuid"
	"gorm.io/gorm"
)

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, input model.CreateUserInput) (*model.AuthPayload, error) {
	// Hash the password
	hashedPassword, err := auth.HashPassword(input.Password)
	if err != nil {
		return nil, fmt.Errorf("failed to hash password: %w", err)
	}

	// Create user
	user := db.User{
		Email:        input.Email,
		PasswordHash: hashedPassword,
		Name:         input.Name,
		Role:         "user",
	}

	if err := r.DB.Create(&user).Error; err != nil {
		return nil, fmt.Errorf("failed to create user: %w", err)
	}

	// Generate JWT token
	token, err := auth.GenerateToken(user.ID, user.Role)
	if err != nil {
		return nil, fmt.Errorf("failed to generate token: %w", err)
	}

	return &model.AuthPayload{
		Token: token,
		User: &model.User{
			ID:           user.ID.String(),
			Email:        user.Email,
			Name:         user.Name,
			Role:         user.Role,
			StorageUsed:  int(user.StorageUsed),
			StorageQuota: int(user.StorageQuota),
			CreatedAt:    user.CreatedAt,
			UpdatedAt:    user.UpdatedAt,
		},
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	// Find user by email
	var user db.User
	if err := r.DB.Where("email = ?", email).First(&user).Error; err != nil {
		// Log failed login attempt
		r.Audit.LogAuthAction(ctx, nil, audit.ActionSecurityFailedLogin, &audit.AuditDetails{
			Metadata: map[string]interface{}{
				"email": email,
				"error": "user not found",
			},
			Success: false,
		})
		return nil, fmt.Errorf("invalid email or password")
	}

	// Check password
	if err := auth.CheckPassword(password, user.PasswordHash); err != nil {
		// Log failed login attempt
		r.Audit.LogAuthAction(ctx, &user.ID, audit.ActionSecurityFailedLogin, &audit.AuditDetails{
			Metadata: map[string]interface{}{
				"email": email,
				"error": "invalid password",
			},
			Success: false,
		})
		return nil, fmt.Errorf("invalid email or password")
	}

	// Generate JWT token
	token, err := auth.GenerateToken(user.ID, user.Role)
	if err != nil {
		return nil, fmt.Errorf("failed to generate token: %w", err)
	}

	// Log successful login
	r.Audit.LogUserAction(ctx, &user.ID, audit.ActionUserLogin, user.ID, &audit.AuditDetails{
		Metadata: map[string]interface{}{
			"email": email,
		},
		Success: true,
	})

	return &model.AuthPayload{
		Token: token,
		User: &model.User{
			ID:           user.ID.String(),
			Email:        user.Email,
			Name:         user.Name,
			Role:         user.Role,
			StorageUsed:  int(user.StorageUsed),
			StorageQuota: int(user.StorageQuota),
			CreatedAt:    user.CreatedAt,
			UpdatedAt:    user.UpdatedAt,
		},
	}, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUserInput) (*model.User, error) {
	// Require authentication
	currentUser, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Only admins can update other users' roles
	if currentUser.Role != "admin" && currentUser.ID.String() != id {
		return nil, fmt.Errorf("unauthorized: only admins can update other users")
	}

	// Find the user to update
	var dbUser db.User
	if err := r.DB.First(&dbUser, "id = ?", id).Error; err != nil {
		return nil, fmt.Errorf("user not found")
	}

	// Update fields if provided
	if input.Name != nil {
		dbUser.Name = *input.Name
	}

	if input.StorageQuota != nil && currentUser.Role == "admin" {
		dbUser.StorageQuota = int64(*input.StorageQuota)
	}

	// Only admins can update roles
	if input.Role != nil && currentUser.Role == "admin" {
		dbUser.Role = *input.Role
	}

	// Save changes
	if err := r.DB.Save(&dbUser).Error; err != nil {
		return nil, fmt.Errorf("failed to update user: %v", err)
	}

	return &model.User{
		ID:           dbUser.ID.String(),
		Email:        dbUser.Email,
		Name:         dbUser.Name,
		Role:         dbUser.Role,
		StorageUsed:  int(dbUser.StorageUsed),
		StorageQuota: int(dbUser.StorageQuota),
		CreatedAt:    dbUser.CreatedAt,
		UpdatedAt:    dbUser.UpdatedAt,
		Files:        []*model.File{},   // Empty to avoid relationship issues
		Folders:      []*model.Folder{}, // Empty to avoid relationship issues
	}, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	// Require authentication
	currentUser, err := RequireAuth(ctx)
	if err != nil {
		return false, err
	}

	// Only allow admin users to delete other users
	if currentUser.Role != "admin" {
		return false, fmt.Errorf("unauthorized: only admin users can delete other users")
	}

	// Parse user ID
	userID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid user ID: %w", err)
	}

	// Prevent admin from deleting themselves
	if currentUser.ID == userID {
		return false, fmt.Errorf("cannot delete your own account")
	}

	// Find the user to delete
	var userToDelete db.User
	if err := r.DB.Where("id = ?", userID).First(&userToDelete).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return false, fmt.Errorf("user not found")
		}
		return false, fmt.Errorf("failed to fetch user: %v", err)
	}

	// Start transaction for cascade deletion
	tx := r.DB.Begin()
	defer func() {
		if r := recover(); r != nil {
			tx.Rollback()
		}
	}()

	// Delete all user's files with deduplication logic
	var userFiles []db.File
	if err := tx.Where("owner_id = ?", userID).Find(&userFiles).Error; err != nil {
		tx.Rollback()
		return false, fmt.Errorf("failed to find user files: %w", err)
	}

	for _, file := range userFiles {
		if err := r.deleteFileWithDeduplication(tx, file); err != nil {
			tx.Rollback()
			return false, fmt.Errorf("failed to delete user file %s: %w", file.Name, err)
		}
	}

	// Delete all user's folders (this will cascade to any remaining files)
	if err := tx.Where("owner_id = ?", userID).Delete(&db.Folder{}).Error; err != nil {
		tx.Rollback()
		return false, fmt.Errorf("failed to delete user folders: %w", err)
	}

	// Delete file shares where this user is involved
	if err := tx.Where("user_id = ?", userID).Delete(&db.FileShare{}).Error; err != nil {
		tx.Rollback()
		return false, fmt.Errorf("failed to delete file shares: %w", err)
	}

	// Delete folder shares where this user is involved
	if err := tx.Where("user_id = ?", userID).Delete(&db.FolderShare{}).Error; err != nil {
		tx.Rollback()
		return false, fmt.Errorf("failed to delete folder shares: %w", err)
	}

	// Finally delete the user record
	if err := tx.Delete(&userToDelete).Error; err != nil {
		tx.Rollback()
		return false, fmt.Errorf("failed to delete user: %w", err)
	}

	// Commit transaction
	if err := tx.Commit().Error; err != nil {
		return false, fmt.Errorf("failed to commit user deletion: %w", err)
	}

	return true, nil
}

// UploadFile is the resolver for the uploadFile field.
func (r *mutationResolver) UploadFile(ctx context.Context, file graphql.Upload, folderID *string, isPublic *bool) (*model.File, error) {
	// Get authenticated user
	user, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Calculate file hash
	contentHash, err := r.Storage.CalculateHash(file.File)
	if err != nil {
		return nil, fmt.Errorf("failed to calculate file hash: %w", err)
	}

	// Get file size by reading to end and back
	currentPos, _ := file.File.Seek(0, io.SeekCurrent)
	fileSize, _ := file.File.Seek(0, io.SeekEnd)
	file.File.Seek(currentPos, io.SeekStart)

	// Check if file content already exists
	var existingContent db.FileContent
	contentExists := r.DB.Where("content_hash = ?", contentHash).First(&existingContent).Error == nil

	// Save file if it doesn't exist
	if !contentExists {
		if err := r.Storage.SaveFile(file.File, contentHash); err != nil {
			return nil, fmt.Errorf("failed to save file: %w", err)
		}

		// Create file content record
		existingContent = db.FileContent{
			ContentHash:    contentHash,
			Path:           r.Storage.GetFilePath(contentHash),
			ReferenceCount: 0,
		}
		if err := r.DB.Create(&existingContent).Error; err != nil {
			return nil, fmt.Errorf("failed to create file content record: %w", err)
		}
	}

	// Check storage quota
	if user.StorageUsed+fileSize > user.StorageQuota {
		return nil, fmt.Errorf("storage quota exceeded")
	}

	// Create file record
	dbFile := db.File{
		Name:        file.Filename,
		ContentHash: contentHash,
		MimeType:    file.ContentType,
		Size:        fileSize,
		OwnerID:     user.ID,
		IsPublic:    isPublic != nil && *isPublic,
	}

	// Set folder if provided
	if folderID != nil {
		folderUUID, err := uuid.Parse(*folderID)
		if err != nil {
			return nil, fmt.Errorf("invalid folder ID: %w", err)
		}
		dbFile.FolderID = &folderUUID
	}

	if err := r.DB.Create(&dbFile).Error; err != nil {
		return nil, fmt.Errorf("failed to create file record: %w", err)
	}

	// Update reference count and user storage
	r.DB.Model(&existingContent).Update("reference_count", gorm.Expr("reference_count + ?", 1))
	r.DB.Model(user).Update("storage_used", gorm.Expr("storage_used + ?", fileSize))

	// Reload file with owner relationship
	if err := r.DB.Preload("Owner").First(&dbFile, dbFile.ID).Error; err != nil {
		return nil, fmt.Errorf("failed to reload file with owner: %w", err)
	}

	// Create model.File for real-time updates
	modelFile := &model.File{
		ID:            dbFile.ID.String(),
		Name:          dbFile.Name,
		ContentHash:   dbFile.ContentHash,
		MimeType:      dbFile.MimeType,
		Size:          int(dbFile.Size),
		IsPublic:      dbFile.IsPublic,
		DownloadCount: dbFile.DownloadCount,
		CreatedAt:     dbFile.CreatedAt,
		UpdatedAt:     dbFile.UpdatedAt,
		Owner: &model.User{
			ID:           dbFile.Owner.ID.String(),
			Email:        dbFile.Owner.Email,
			Name:         dbFile.Owner.Name,
			Role:         dbFile.Owner.Role,
			StorageUsed:  int(dbFile.Owner.StorageUsed),
			StorageQuota: int(dbFile.Owner.StorageQuota),
			CreatedAt:    dbFile.Owner.CreatedAt,
			UpdatedAt:    dbFile.Owner.UpdatedAt,
		},
	}

	// Log audit event
	r.Audit.LogFileOperation(ctx, &user.ID, audit.ActionFileUpload, dbFile.ID, dbFile.Name, dbFile.Size, dbFile.MimeType)

	// Publish real-time events
	realtime.GlobalPublisher.PublishFileUpdate(modelFile)
	
	// Publish activity event
	activityEvent := realtime.CreateActivityEvent(
		realtime.EventFileUploaded,
		user.ID.String(),
		user.Name,
		fmt.Sprintf("%s uploaded a new file: %s", user.Name, dbFile.Name),
		nil,
	)
	realtime.GlobalPublisher.PublishActivity(activityEvent)

	return modelFile, nil
}

// UpdateFile is the resolver for the updateFile field.
func (r *mutationResolver) UpdateFile(ctx context.Context, id string, name *string, isPublic *bool) (*model.File, error) {
	// Get current user from context
	user, err := GetUserFromContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("authentication required")
	}

	// Parse file ID
	fileID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid file ID")
	}

	// Get the file and verify ownership
	var file db.File
	if err := r.DB.Where("id = ? AND owner_id = ?", fileID, user.ID).First(&file).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return nil, fmt.Errorf("file not found or access denied")
		}
		return nil, fmt.Errorf("failed to fetch file: %w", err)
	}

	// Update fields if provided
	if name != nil {
		file.Name = *name
	}
	if isPublic != nil {
		file.IsPublic = *isPublic
	}

	// Save changes
	if err := r.DB.Save(&file).Error; err != nil {
		return nil, fmt.Errorf("failed to update file: %w", err)
	}

	// Load owner information for response
	if err := r.DB.Preload("Owner").First(&file, file.ID).Error; err != nil {
		return nil, fmt.Errorf("failed to load updated file: %w", err)
	}

	// Convert to model
	return &model.File{
		ID:            file.ID.String(),
		Name:          file.Name,
		ContentHash:   file.ContentHash,
		MimeType:      file.MimeType,
		Size:          int(file.Size),
		IsPublic:      file.IsPublic,
		DownloadCount: int(file.DownloadCount),
		CreatedAt:     file.CreatedAt,
		UpdatedAt:     file.UpdatedAt,
		Owner: &model.User{
			ID:    file.Owner.ID.String(),
			Name:  file.Owner.Name,
			Email: file.Owner.Email,
		},
	}, nil
}

// DeleteFile is the resolver for the deleteFile field.
func (r *mutationResolver) DeleteFile(ctx context.Context, id string) (bool, error) {
	user, err := RequireAuth(ctx)
	if err != nil {
		return false, err
	}

	fileUUID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid file ID: %w", err)
	}

	// First check if file exists at all
	var file db.File
	if err := r.DB.Where("id = ?", fileUUID).First(&file).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return false, fmt.Errorf("FILE_NOT_FOUND: The file you're trying to delete does not exist or has already been deleted")
		}
		return false, fmt.Errorf("DATABASE_ERROR: Failed to check file existence: %w", err)
	}

	// Check ownership
	if file.OwnerID != user.ID {
		// Get file owner info for better error message
		var owner db.User
		r.DB.Where("id = ?", file.OwnerID).First(&owner)
		return false, fmt.Errorf("ACCESS_DENIED: You cannot delete '%s' because it belongs to %s. Only the file owner can delete this file", file.Name, owner.Name)
	}

	// Get file content info
	var content db.FileContent
	if err := r.DB.Where("content_hash = ?", file.ContentHash).First(&content).Error; err != nil {
		return false, fmt.Errorf("file content not found: %w", err)
	}

	// Start transaction
	tx := r.DB.Begin()

	// Delete file record
	if err := tx.Delete(&file).Error; err != nil {
		tx.Rollback()
		return false, fmt.Errorf("failed to delete file record: %w", err)
	}

	// Update reference count
	if err := tx.Model(&content).Update("reference_count", gorm.Expr("reference_count - ?", 1)).Error; err != nil {
		tx.Rollback()
		return false, fmt.Errorf("failed to update reference count: %w", err)
	}

	// Update user storage
	if err := tx.Model(user).Update("storage_used", gorm.Expr("storage_used - ?", file.Size)).Error; err != nil {
		tx.Rollback()
		return false, fmt.Errorf("failed to update user storage: %w", err)
	}

	// If no more references, delete the actual file
	var updatedContent db.FileContent
	if err := tx.Where("content_hash = ?", file.ContentHash).First(&updatedContent).Error; err == nil {
		if updatedContent.ReferenceCount <= 0 {
			// Delete file from storage
			if err := r.Storage.DeleteFile(file.ContentHash); err != nil {
				tx.Rollback()
				return false, fmt.Errorf("failed to delete file from storage: %w", err)
			}
			// Delete content record
			if err := tx.Delete(&updatedContent).Error; err != nil {
				tx.Rollback()
				return false, fmt.Errorf("failed to delete content record: %w", err)
			}
		}
	}

	tx.Commit()
	
	// Log audit event
	r.Audit.LogFileOperation(ctx, &user.ID, audit.ActionFileDelete, file.ID, file.Name, file.Size, file.MimeType)
	
	// Publish real-time events after successful deletion
	activityEvent := realtime.CreateActivityEvent(
		realtime.EventFileDeleted,
		user.ID.String(),
		user.Name,
		fmt.Sprintf("%s deleted file: %s", user.Name, file.Name),
		nil,
	)
	realtime.GlobalPublisher.PublishActivity(activityEvent)

	return true, nil
}

// ShareFile is the resolver for the shareFile field.
func (r *mutationResolver) ShareFile(ctx context.Context, id string, userID string) (*model.FileShare, error) {
	user, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Parse UUIDs
	fileUUID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid file ID: %w", err)
	}

	targetUserUUID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	// Verify file exists and user owns it
	var dbFile db.File
	if err := r.DB.Where("id = ? AND owner_id = ?", fileUUID, user.ID).First(&dbFile).Error; err != nil {
		return nil, fmt.Errorf("file not found or access denied")
	}

	// Verify target user exists
	var targetUser db.User
	if err := r.DB.Where("id = ?", targetUserUUID).First(&targetUser).Error; err != nil {
		return nil, fmt.Errorf("target user not found")
	}

	// Check if already shared
	var existingShare db.FileShare
	if err := r.DB.Where("file_id = ? AND user_id = ?", fileUUID, targetUserUUID).First(&existingShare).Error; err == nil {
		return nil, fmt.Errorf("file is already shared with this user")
	}

	// Create new share
	share := db.FileShare{
		ID:     uuid.New(),
		FileID: fileUUID,
		UserID: targetUserUUID,
	}

	if err := r.DB.Create(&share).Error; err != nil {
		return nil, fmt.Errorf("failed to create file share: %w", err)
	}

	// Load the share with relationships
	if err := r.DB.Preload("File").Preload("User").Where("id = ?", share.ID).First(&share).Error; err != nil {
		return nil, fmt.Errorf("failed to load created share: %w", err)
	}

	result := &model.FileShare{
		ID: share.ID.String(),
		File: &model.File{
			ID:            share.File.ID.String(),
			Name:          share.File.Name,
			ContentHash:   share.File.ContentHash,
			MimeType:      share.File.MimeType,
			Size:          int(share.File.Size),
			IsPublic:      share.File.IsPublic,
			DownloadCount: int(share.File.DownloadCount),
			CreatedAt:     share.File.CreatedAt,
			UpdatedAt:     share.File.UpdatedAt,
		},
		User: &model.User{
			ID:           share.User.ID.String(),
			Email:        share.User.Email,
			Name:         share.User.Name,
			Role:         share.User.Role,
			StorageUsed:  int(share.User.StorageUsed),
			StorageQuota: int(share.User.StorageQuota),
			CreatedAt:    share.User.CreatedAt,
			UpdatedAt:    share.User.UpdatedAt,
		},
		CreatedAt: share.CreatedAt,
		UpdatedAt: share.UpdatedAt,
	}

	// Publish real-time events
	activityEvent := realtime.CreateActivityEvent(
		realtime.EventFileShared,
		user.ID.String(),
		user.Name,
		fmt.Sprintf("%s shared file '%s' with %s", user.Name, share.File.Name, share.User.Name),
		nil,
	)
	realtime.GlobalPublisher.PublishActivity(activityEvent)

	return result, nil
}

// UnshareFile is the resolver for the unshareFile field.
func (r *mutationResolver) UnshareFile(ctx context.Context, id string, userID string) (bool, error) {
	user, err := RequireAuth(ctx)
	if err != nil {
		return false, err
	}

	// Parse UUIDs
	fileUUID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid file ID: %w", err)
	}

	targetUserUUID, err := uuid.Parse(userID)
	if err != nil {
		return false, fmt.Errorf("invalid user ID: %w", err)
	}

	// Verify file exists and user owns it
	var dbFile db.File
	if err := r.DB.Where("id = ? AND owner_id = ?", fileUUID, user.ID).First(&dbFile).Error; err != nil {
		return false, fmt.Errorf("file not found or access denied")
	}

	// Delete the share
	result := r.DB.Where("file_id = ? AND user_id = ?", fileUUID, targetUserUUID).Delete(&db.FileShare{})
	if result.Error != nil {
		return false, fmt.Errorf("failed to unshare file: %w", result.Error)
	}

	return result.RowsAffected > 0, nil
}

// CreateFolder is the resolver for the createFolder field.
func (r *mutationResolver) CreateFolder(ctx context.Context, input model.CreateFolderInput) (*model.Folder, error) {
	user, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	folder := db.Folder{
		Name:     input.Name,
		OwnerID:  user.ID,
		IsPublic: input.IsPublic != nil && *input.IsPublic,
	}

	// Set parent folder if provided
	if input.ParentID != nil {
		parentUUID, err := uuid.Parse(*input.ParentID)
		if err != nil {
			return nil, fmt.Errorf("invalid parent folder ID: %w", err)
		}

		// Verify parent folder exists and user has access
		var parentFolder db.Folder
		if err := r.DB.Where("id = ? AND owner_id = ?", parentUUID, user.ID).First(&parentFolder).Error; err != nil {
			return nil, fmt.Errorf("parent folder not found or access denied")
		}

		folder.ParentID = &parentUUID
	}

	if err := r.DB.Create(&folder).Error; err != nil {
		return nil, fmt.Errorf("failed to create folder: %w", err)
	}

	// Load the folder with the owner relationship
	if err := r.DB.Preload("Owner").First(&folder, folder.ID).Error; err != nil {
		return nil, fmt.Errorf("failed to load created folder: %w", err)
	}

	result := &model.Folder{
		ID:   folder.ID.String(),
		Name: folder.Name,
		Owner: &model.User{
			ID:           folder.Owner.ID.String(),
			Email:        folder.Owner.Email,
			Name:         folder.Owner.Name,
			Role:         folder.Owner.Role,
			StorageUsed:  int(folder.Owner.StorageUsed),
			StorageQuota: int(folder.Owner.StorageQuota),
			CreatedAt:    folder.Owner.CreatedAt,
			UpdatedAt:    folder.Owner.UpdatedAt,
		},
		IsPublic:  folder.IsPublic,
		CreatedAt: folder.CreatedAt,
		UpdatedAt: folder.UpdatedAt,
	}

	// Publish real-time events
	realtime.GlobalPublisher.PublishFolderUpdate(result)
	
	activityEvent := realtime.CreateActivityEvent(
		realtime.EventFolderCreated,
		user.ID.String(),
		user.Name,
		fmt.Sprintf("%s created folder: %s", user.Name, folder.Name),
		nil,
	)
	realtime.GlobalPublisher.PublishActivity(activityEvent)

	return result, nil
}

// UpdateFolder is the resolver for the updateFolder field.
func (r *mutationResolver) UpdateFolder(ctx context.Context, id string, input model.UpdateFolderInput) (*model.Folder, error) {
	user, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Parse folder ID
	folderID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid folder ID: %w", err)
	}

	// Find the folder and verify ownership
	var folder db.Folder
	if err := r.DB.Where("id = ? AND owner_id = ?", folderID, user.ID).First(&folder).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return nil, fmt.Errorf("folder not found or access denied")
		}
		return nil, fmt.Errorf("failed to fetch folder: %w", err)
	}

	// Update fields if provided
	if input.Name != nil {
		folder.Name = *input.Name
	}

	if input.IsPublic != nil {
		folder.IsPublic = *input.IsPublic
	}

	if input.ParentID != nil {
		parentUUID, err := uuid.Parse(*input.ParentID)
		if err != nil {
			return nil, fmt.Errorf("invalid parent folder ID: %w", err)
		}

		// Verify parent folder exists and user has access
		var parentFolder db.Folder
		if err := r.DB.Where("id = ? AND owner_id = ?", parentUUID, user.ID).First(&parentFolder).Error; err != nil {
			return nil, fmt.Errorf("parent folder not found or access denied")
		}

		folder.ParentID = &parentUUID
	}

	// Save changes
	if err := r.DB.Save(&folder).Error; err != nil {
		return nil, fmt.Errorf("failed to update folder: %w", err)
	}

	// Load the folder with the owner relationship for response
	if err := r.DB.Preload("Owner").First(&folder, folder.ID).Error; err != nil {
		return nil, fmt.Errorf("failed to load updated folder: %w", err)
	}

	return &model.Folder{
		ID:   folder.ID.String(),
		Name: folder.Name,
		Owner: &model.User{
			ID:           folder.Owner.ID.String(),
			Email:        folder.Owner.Email,
			Name:         folder.Owner.Name,
			Role:         folder.Owner.Role,
			StorageUsed:  int(folder.Owner.StorageUsed),
			StorageQuota: int(folder.Owner.StorageQuota),
			CreatedAt:    folder.Owner.CreatedAt,
			UpdatedAt:    folder.Owner.UpdatedAt,
		},
		IsPublic:  folder.IsPublic,
		CreatedAt: folder.CreatedAt,
		UpdatedAt: folder.UpdatedAt,
	}, nil
}

// DeleteFolder is the resolver for the deleteFolder field.
func (r *mutationResolver) DeleteFolder(ctx context.Context, id string) (bool, error) {
	user, err := RequireAuth(ctx)
	if err != nil {
		return false, err
	}

	// Parse folder UUID
	folderUUID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("INVALID_ID: Invalid folder ID format")
	}

	// First check if folder exists at all
	var folder db.Folder
	if err := r.DB.Where("id = ?", folderUUID).First(&folder).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return false, fmt.Errorf("FOLDER_NOT_FOUND: The folder you're trying to delete does not exist or has already been deleted")
		}
		return false, fmt.Errorf("DATABASE_ERROR: Failed to check folder existence: %w", err)
	}

	// Check ownership
	if folder.OwnerID != user.ID {
		// Get folder owner info for better error message
		var owner db.User
		r.DB.Where("id = ?", folder.OwnerID).First(&owner)
		return false, fmt.Errorf("ACCESS_DENIED: You cannot delete folder '%s' because it belongs to %s. Only the folder owner can delete this folder", folder.Name, owner.Name)
	}

	// Start transaction for cascade deletion
	tx := r.DB.Begin()
	defer func() {
		if r := recover(); r != nil {
			tx.Rollback()
		}
	}()

	// Get all files in this folder (including subfolders recursively)
	var filesToDelete []db.File
	if err := r.getAllFilesInFolder(tx, folderUUID.String(), &filesToDelete); err != nil {
		tx.Rollback()
		return false, fmt.Errorf("failed to get files in folder: %w", err)
	}

	// Delete all files with deduplication logic
	for _, file := range filesToDelete {
		if err := r.deleteFileWithDeduplication(tx, file); err != nil {
			tx.Rollback()
			return false, fmt.Errorf("failed to delete file %s: %w", file.Name, err)
		}
	}

	// Delete all subfolders recursively
	if err := tx.Where("parent_id = ?", folderUUID).Delete(&db.Folder{}).Error; err != nil {
		tx.Rollback()
		return false, fmt.Errorf("failed to delete subfolders: %w", err)
	}

	// Delete the folder itself
	if err := tx.Delete(&folder).Error; err != nil {
		tx.Rollback()
		return false, fmt.Errorf("failed to delete folder: %w", err)
	}

	// Commit transaction
	if err := tx.Commit().Error; err != nil {
		return false, fmt.Errorf("failed to commit deletion: %w", err)
	}

	return true, nil
}

// ShareFolder is the resolver for the shareFolder field.
func (r *mutationResolver) ShareFolder(ctx context.Context, id string, userID string) (*model.FolderShare, error) {
	user, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Parse UUIDs
	folderUUID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid folder ID: %w", err)
	}

	targetUserUUID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	// Verify folder exists and user owns it
	var dbFolder db.Folder
	if err := r.DB.Where("id = ? AND owner_id = ?", folderUUID, user.ID).First(&dbFolder).Error; err != nil {
		return nil, fmt.Errorf("folder not found or access denied")
	}

	// Verify target user exists
	var targetUser db.User
	if err := r.DB.Where("id = ?", targetUserUUID).First(&targetUser).Error; err != nil {
		return nil, fmt.Errorf("target user not found")
	}

	// Check if already shared
	var existingShare db.FolderShare
	if err := r.DB.Where("folder_id = ? AND user_id = ?", folderUUID, targetUserUUID).First(&existingShare).Error; err == nil {
		return nil, fmt.Errorf("folder is already shared with this user")
	}

	// Create new share
	share := db.FolderShare{
		ID:       uuid.New(),
		FolderID: folderUUID,
		UserID:   targetUserUUID,
	}

	if err := r.DB.Create(&share).Error; err != nil {
		return nil, fmt.Errorf("failed to create folder share: %w", err)
	}

	// Load the share with relationships
	if err := r.DB.Preload("Folder").Preload("User").Where("id = ?", share.ID).First(&share).Error; err != nil {
		return nil, fmt.Errorf("failed to load created share: %w", err)
	}

	return &model.FolderShare{
		ID: share.ID.String(),
		Folder: &model.Folder{
			ID:        share.Folder.ID.String(),
			Name:      share.Folder.Name,
			IsPublic:  share.Folder.IsPublic,
			CreatedAt: share.Folder.CreatedAt,
			UpdatedAt: share.Folder.UpdatedAt,
		},
		User: &model.User{
			ID:           share.User.ID.String(),
			Email:        share.User.Email,
			Name:         share.User.Name,
			Role:         share.User.Role,
			StorageUsed:  int(share.User.StorageUsed),
			StorageQuota: int(share.User.StorageQuota),
			CreatedAt:    share.User.CreatedAt,
			UpdatedAt:    share.User.UpdatedAt,
		},
		CreatedAt: share.CreatedAt,
		UpdatedAt: share.UpdatedAt,
	}, nil
}

// UnshareFolder is the resolver for the unshareFolder field.
func (r *mutationResolver) UnshareFolder(ctx context.Context, id string, userID string) (bool, error) {
	user, err := RequireAuth(ctx)
	if err != nil {
		return false, err
	}

	// Parse UUIDs
	folderUUID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid folder ID: %w", err)
	}

	targetUserUUID, err := uuid.Parse(userID)
	if err != nil {
		return false, fmt.Errorf("invalid user ID: %w", err)
	}

	// Verify folder exists and user owns it
	var dbFolder db.Folder
	if err := r.DB.Where("id = ? AND owner_id = ?", folderUUID, user.ID).First(&dbFolder).Error; err != nil {
		return false, fmt.Errorf("folder not found or access denied")
	}

	// Delete the share
	result := r.DB.Where("folder_id = ? AND user_id = ?", folderUUID, targetUserUUID).Delete(&db.FolderShare{})
	if result.Error != nil {
		return false, fmt.Errorf("failed to unshare folder: %w", result.Error)
	}

	return result.RowsAffected > 0, nil
}

// CreateTag is the resolver for the createTag field.
func (r *mutationResolver) CreateTag(ctx context.Context, name string) (*model.Tag, error) {
	panic(fmt.Errorf("not implemented: CreateTag - createTag"))
}

// AddTagToFile is the resolver for the addTagToFile field.
func (r *mutationResolver) AddTagToFile(ctx context.Context, fileID string, tagID string) (*model.File, error) {
	panic(fmt.Errorf("not implemented: AddTagToFile - addTagToFile"))
}

// RemoveTagFromFile is the resolver for the removeTagFromFile field.
func (r *mutationResolver) RemoveTagFromFile(ctx context.Context, fileID string, tagID string) (*model.File, error) {
	panic(fmt.Errorf("not implemented: RemoveTagFromFile - removeTagFromFile"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	user, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	return &model.User{
		ID:           user.ID.String(),
		Email:        user.Email,
		Name:         user.Name,
		Role:         user.Role,
		StorageUsed:  int(user.StorageUsed),
		StorageQuota: int(user.StorageQuota),
		CreatedAt:    user.CreatedAt,
		UpdatedAt:    user.UpdatedAt,
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	// Require authentication
	currentUser, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Only allow admin users to view other user details
	if currentUser.Role != "admin" {
		return nil, fmt.Errorf("unauthorized: only admin users can view user details")
	}

	// Parse user ID
	userID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid user ID: %w", err)
	}

	var dbUser db.User
	if err := r.DB.Where("id = ?", userID).First(&dbUser).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return nil, fmt.Errorf("user not found")
		}
		return nil, fmt.Errorf("failed to fetch user: %v", err)
	}

	return &model.User{
		ID:           dbUser.ID.String(),
		Email:        dbUser.Email,
		Name:         dbUser.Name,
		Role:         dbUser.Role,
		StorageUsed:  int(dbUser.StorageUsed),
		StorageQuota: int(dbUser.StorageQuota),
		CreatedAt:    dbUser.CreatedAt,
		UpdatedAt:    dbUser.UpdatedAt,
		Files:        []*model.File{},   // Empty to avoid relationship issues
		Folders:      []*model.Folder{}, // Empty to avoid relationship issues
	}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	// Require authentication
	currentUser, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Only allow admin users to list all users
	if currentUser.Role != "admin" {
		return nil, fmt.Errorf("unauthorized: only admin users can list all users")
	}

	var dbUsers []db.User
	if err := r.DB.Find(&dbUsers).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch users: %v", err)
	}

	// Convert to model.User without preloading relationships
	var users []*model.User
	for _, dbUser := range dbUsers {
		users = append(users, &model.User{
			ID:           dbUser.ID.String(),
			Email:        dbUser.Email,
			Name:         dbUser.Name,
			Role:         dbUser.Role,
			StorageUsed:  int(dbUser.StorageUsed),
			StorageQuota: int(dbUser.StorageQuota),
			CreatedAt:    dbUser.CreatedAt,
			UpdatedAt:    dbUser.UpdatedAt,
			Files:        []*model.File{},   // Empty array to avoid relationship issues
			Folders:      []*model.Folder{}, // Empty array to avoid relationship issues
		})
	}

	return users, nil
}

// File is the resolver for the file field.
func (r *queryResolver) File(ctx context.Context, id string) (*model.File, error) {
	panic(fmt.Errorf("not implemented: File - file"))
}

// Files is the resolver for the files field.
func (r *queryResolver) Files(ctx context.Context, filter *model.FileFilter, first *int, after *string) ([]*model.File, error) {
	user, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	query := r.DB.Where("owner_id = ? OR is_public = ?", user.ID, true)

	// Apply filters if provided
	if filter != nil {
		if filter.Filename != nil {
			query = query.Where("name ILIKE ?", "%"+*filter.Filename+"%")
		}
		if filter.MimeType != nil {
			if strings.HasSuffix(*filter.MimeType, "/") {
				// Filter by MIME type prefix (e.g., "image/")
				query = query.Where("mime_type LIKE ?", *filter.MimeType+"%")
			} else {
				// Filter by exact MIME type
				query = query.Where("mime_type = ?", *filter.MimeType)
			}
		}
		if filter.MinSize != nil {
			query = query.Where("size >= ?", *filter.MinSize)
		}
		if filter.MaxSize != nil {
			query = query.Where("size <= ?", *filter.MaxSize)
		}
		if filter.FromDate != nil {
			query = query.Where("created_at >= ?", *filter.FromDate)
		}
		if filter.ToDate != nil {
			query = query.Where("created_at <= ?", *filter.ToDate)
		}
		if filter.Uploader != nil {
			// Join with users table to filter by uploader name
			query = query.Joins("JOIN users ON files.owner_id = users.id").
				Where("users.name ILIKE ?", "%"+*filter.Uploader+"%")
		}
		// TODO: Add tags filter when tag relationships are implemented
	}

	// Apply pagination
	limit := 10 // default
	if first != nil && *first > 0 {
		limit = *first
	}
	query = query.Limit(limit).Preload("Owner")

	var files []db.File
	if err := query.Find(&files).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch files: %w", err)
	}

	var result []*model.File
	for _, file := range files {
		result = append(result, &model.File{
			ID:            file.ID.String(),
			Name:          file.Name,
			ContentHash:   file.ContentHash,
			MimeType:      file.MimeType,
			Size:          int(file.Size),
			IsPublic:      file.IsPublic,
			DownloadCount: file.DownloadCount,
			CreatedAt:     file.CreatedAt,
			UpdatedAt:     file.UpdatedAt,
			Owner: &model.User{
				ID:           file.Owner.ID.String(),
				Email:        file.Owner.Email,
				Name:         file.Owner.Name,
				Role:         file.Owner.Role,
				StorageUsed:  int(file.Owner.StorageUsed),
				StorageQuota: int(file.Owner.StorageQuota),
				CreatedAt:    file.Owner.CreatedAt,
				UpdatedAt:    file.Owner.UpdatedAt,
			},
		})
	}

	return result, nil
}

// Folder is the resolver for the folder field.
func (r *queryResolver) Folder(ctx context.Context, id string) (*model.Folder, error) {
	user, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	var folder db.Folder
	err = r.DB.Preload("Owner").Preload("Parent").Preload("Files").Preload("Files.Owner").Where("id = ? AND (owner_id = ? OR is_public = ?)", id, user.ID, true).First(&folder).Error
	if err != nil {
		return nil, err
	}

	// Convert parent if exists
	var parent *model.Folder
	if folder.Parent != nil {
		parent = &model.Folder{
			ID:   folder.Parent.ID.String(),
			Name: folder.Parent.Name,
		}
	}

	// Convert files
	var files []*model.File
	for _, file := range folder.Files {
		var fileFolder *model.Folder
		if file.Folder != nil {
			fileFolder = &model.Folder{
				ID:   file.Folder.ID.String(),
				Name: file.Folder.Name,
			}
		}

		files = append(files, &model.File{
			ID:            file.ID.String(),
			Name:          file.Name,
			ContentHash:   file.ContentHash,
			MimeType:      file.MimeType,
			Size:          int(file.Size),
			IsPublic:      file.IsPublic,
			DownloadCount: file.DownloadCount,
			CreatedAt:     file.CreatedAt,
			UpdatedAt:     file.UpdatedAt,
			Owner: &model.User{
				ID:           file.Owner.ID.String(),
				Name:         file.Owner.Name,
				Email:        file.Owner.Email,
				Role:         file.Owner.Role,
				StorageUsed:  int(file.Owner.StorageUsed),
				StorageQuota: int(file.Owner.StorageQuota),
				CreatedAt:    file.Owner.CreatedAt,
				UpdatedAt:    file.Owner.UpdatedAt,
			},
			Folder: fileFolder,
		})
	}

	return &model.Folder{
		ID:        folder.ID.String(),
		Name:      folder.Name,
		IsPublic:  folder.IsPublic,
		CreatedAt: folder.CreatedAt,
		UpdatedAt: folder.UpdatedAt,
		Owner: &model.User{
			ID:           folder.Owner.ID.String(),
			Name:         folder.Owner.Name,
			Email:        folder.Owner.Email,
			Role:         folder.Owner.Role,
			StorageUsed:  int(folder.Owner.StorageUsed),
			StorageQuota: int(folder.Owner.StorageQuota),
			CreatedAt:    folder.Owner.CreatedAt,
			UpdatedAt:    folder.Owner.UpdatedAt,
		},
		Parent: parent,
		Files:  files,
	}, nil
}

// Folders is the resolver for the folders field.
func (r *queryResolver) Folders(ctx context.Context) ([]*model.Folder, error) {
	user, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	var folders []db.Folder
	if err := r.DB.Where("owner_id = ?", user.ID).
		Preload("Owner").
		Preload("Parent").
		Find(&folders).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch folders: %w", err)
	}

	var result []*model.Folder
	for _, folder := range folders {
		var parent *model.Folder
		if folder.Parent != nil {
			parent = &model.Folder{
				ID:   folder.Parent.ID.String(),
				Name: folder.Parent.Name,
			}
		}

		result = append(result, &model.Folder{
			ID:       folder.ID.String(),
			Name:     folder.Name,
			IsPublic: folder.IsPublic,
			Owner: &model.User{
				ID:    folder.Owner.ID.String(),
				Name:  folder.Owner.Name,
				Email: folder.Owner.Email,
			},
			Parent:    parent,
			CreatedAt: folder.CreatedAt,
			UpdatedAt: folder.UpdatedAt,
		})
	}

	return result, nil
}

// PublicFolder is the resolver for the publicFolder field.
func (r *queryResolver) PublicFolder(ctx context.Context, id string) (*model.Folder, error) {
	var folder db.Folder
	if err := r.DB.Preload("Owner").Preload("Files").Preload("Subfolders").Where("id = ? AND is_public = ?", id, true).First(&folder).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("public folder not found")
		}
		return nil, fmt.Errorf("failed to fetch public folder: %w", err)
	}

	return &model.Folder{
		ID:        folder.ID.String(),
		Name:      folder.Name,
		IsPublic:  folder.IsPublic,
		CreatedAt: folder.CreatedAt,
		UpdatedAt: folder.UpdatedAt,
		Owner: &model.User{
			ID:    folder.Owner.ID.String(),
			Email: folder.Owner.Email,
			Name:  folder.Owner.Name,
			Role:  folder.Owner.Role,
		},
		Files: func() []*model.File {
			files := make([]*model.File, len(folder.Files))
			for i, file := range folder.Files {
				files[i] = &model.File{
					ID:            file.ID.String(),
					Name:          file.Name,
					ContentHash:   file.ContentHash,
					MimeType:      file.MimeType,
					Size:          int(file.Size),
					IsPublic:      file.IsPublic,
					DownloadCount: int(file.DownloadCount),
					CreatedAt:     file.CreatedAt,
					UpdatedAt:     file.UpdatedAt,
				}
			}
			return files
		}(),
		Subfolders: func() []*model.Folder {
			subfolders := make([]*model.Folder, len(folder.Subfolders))
			for i, subfolder := range folder.Subfolders {
				subfolders[i] = &model.Folder{
					ID:        subfolder.ID.String(),
					Name:      subfolder.Name,
					IsPublic:  subfolder.IsPublic,
					CreatedAt: subfolder.CreatedAt,
					UpdatedAt: subfolder.UpdatedAt,
				}
			}
			return subfolders
		}(),
	}, nil
}

// SharedFiles is the resolver for the sharedFiles field.
func (r *queryResolver) SharedFiles(ctx context.Context) ([]*model.File, error) {
	user, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Get all files shared with this user
	var fileShares []db.FileShare
	if err := r.DB.Preload("File").Preload("File.Owner").Where("user_id = ?", user.ID).Find(&fileShares).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch shared files: %w", err)
	}

	// Convert to model files
	var files []*model.File
	for _, share := range fileShares {
		files = append(files, &model.File{
			ID:            share.File.ID.String(),
			Name:          share.File.Name,
			ContentHash:   share.File.ContentHash,
			MimeType:      share.File.MimeType,
			Size:          int(share.File.Size),
			IsPublic:      share.File.IsPublic,
			DownloadCount: int(share.File.DownloadCount),
			CreatedAt:     share.File.CreatedAt,
			UpdatedAt:     share.File.UpdatedAt,
		})
	}

	return files, nil
}

// SharedFolders is the resolver for the sharedFolders field.
func (r *queryResolver) SharedFolders(ctx context.Context) ([]*model.Folder, error) {
	user, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Get all folders shared with this user
	var folderShares []db.FolderShare
	if err := r.DB.Preload("Folder").Preload("Folder.Owner").Where("user_id = ?", user.ID).Find(&folderShares).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch shared folders: %w", err)
	}

	// Convert to model folders
	var folders []*model.Folder
	for _, share := range folderShares {
		folders = append(folders, &model.Folder{
			ID:        share.Folder.ID.String(),
			Name:      share.Folder.Name,
			IsPublic:  share.Folder.IsPublic,
			CreatedAt: share.Folder.CreatedAt,
			UpdatedAt: share.Folder.UpdatedAt,
		})
	}

	return folders, nil
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context) ([]*model.Tag, error) {
	panic(fmt.Errorf("not implemented: Tags - tags"))
}

// StorageStats is the resolver for the storageStats field.
func (r *queryResolver) StorageStats(ctx context.Context) (*model.StorageStats, error) {
	user, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Calculate original storage (sum of all file sizes)
	var totalOriginalSize int64
	r.DB.Model(&db.File{}).Select("COALESCE(SUM(size), 0)").
		Where("owner_id = ?", user.ID).Row().Scan(&totalOriginalSize)

	// Calculate deduplicated storage (sum of unique file sizes by content_hash)
	var totalDeduplicatedSize int64
	r.DB.Raw(`
		SELECT COALESCE(SUM(size), 0) 
		FROM (
			SELECT DISTINCT content_hash, size 
			FROM files 
			WHERE owner_id = ?
		) as unique_files
	`, user.ID).Row().Scan(&totalDeduplicatedSize)

	savedStorage := totalOriginalSize - totalDeduplicatedSize
	savingsPercentage := float64(0)
	if totalOriginalSize > 0 {
		savingsPercentage = float64(savedStorage) / float64(totalOriginalSize) * 100
	}

	return &model.StorageStats{
		TotalStorage:      int(totalDeduplicatedSize),
		OriginalStorage:   int(totalOriginalSize),
		SavedStorage:      int(savedStorage),
		SavingsPercentage: savingsPercentage,
	}, nil
}

// AnalyticsSummary is the resolver for the analyticsSummary field.
func (r *queryResolver) AnalyticsSummary(ctx context.Context, days *int) (*model.AnalyticsSummary, error) {
	// Check if user is admin
	user, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	if user.Role != "admin" {
		return nil, errors.New("ACCESS_DENIED: Only admins can access analytics data")
	}

	defaultDays := 30
	if days != nil {
		defaultDays = *days
	}

	// Get all analytics data
	uploadTrends, err := r.getUploadTrends(defaultDays)
	if err != nil {
		return nil, fmt.Errorf("failed to get upload trends: %w", err)
	}

	userActivity, err := r.getUserActivity()
	if err != nil {
		return nil, fmt.Errorf("failed to get user activity: %w", err)
	}

	fileTypeStats, err := r.getFileTypeStats()
	if err != nil {
		return nil, fmt.Errorf("failed to get file type stats: %w", err)
	}

	sharingStats, err := r.getSharingStats()
	if err != nil {
		return nil, fmt.Errorf("failed to get sharing stats: %w", err)
	}

	storageStats, err := r.StorageStats(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to get storage stats: %w", err)
	}

	return &model.AnalyticsSummary{
		UploadTrends:  uploadTrends,
		UserActivity:  userActivity,
		FileTypeStats: fileTypeStats,
		SharingStats:  sharingStats,
		StorageStats:  storageStats,
	}, nil
}

// UploadTrends is the resolver for the uploadTrends field.
func (r *queryResolver) UploadTrends(ctx context.Context, days *int) ([]*model.UploadTrend, error) {
	// Check if user is admin
	user, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	if user.Role != "admin" {
		return nil, errors.New("ACCESS_DENIED: Only admins can access analytics data")
	}

	defaultDays := 30
	if days != nil {
		defaultDays = *days
	}

	return r.getUploadTrends(defaultDays)
}

// UserActivity is the resolver for the userActivity field.
func (r *queryResolver) UserActivity(ctx context.Context) ([]*model.UserActivity, error) {
	// Check if user is admin
	user, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	if user.Role != "admin" {
		return nil, errors.New("ACCESS_DENIED: Only admins can access analytics data")
	}

	return r.getUserActivity()
}

// FileTypeStats is the resolver for the fileTypeStats field.
func (r *queryResolver) FileTypeStats(ctx context.Context) ([]*model.FileTypeStats, error) {
	// Check if user is admin
	user, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	if user.Role != "admin" {
		return nil, errors.New("ACCESS_DENIED: Only admins can access analytics data")
	}

	return r.getFileTypeStats()
}

// SharingStats is the resolver for the sharingStats field.
func (r *queryResolver) SharingStats(ctx context.Context) (*model.SharingStats, error) {
	// Check if user is admin
	user, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	if user.Role != "admin" {
		return nil, errors.New("ACCESS_DENIED: Only admins can access analytics data")
	}

	return r.getSharingStats()
}

// AuditLogs is the resolver for the auditLogs field.
func (r *queryResolver) AuditLogs(ctx context.Context, resourceID *string) ([]*model.AuditLog, error) {
	user, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Only admins can view all audit logs
	if user.Role != "admin" && user.Role != "moderator" {
		return nil, fmt.Errorf("insufficient permissions")
	}

	var logs []*db.AuditLog
	query := r.DB.Preload("User").Order("created_at DESC")

	// Filter by resource ID if provided
	if resourceID != nil {
		query = query.Where("resource_id = ?", *resourceID)
	}

	// Limit to recent 1000 logs to avoid performance issues
	query = query.Limit(1000)

	if err := query.Find(&logs).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch audit logs: %w", err)
	}

	// Convert to GraphQL models
	var result []*model.AuditLog
	for _, log := range logs {
		var user *model.User
		if log.User != nil {
			user = &model.User{
				ID:           log.User.ID.String(),
				Email:        log.User.Email,
				Name:         log.User.Name,
				Role:         log.User.Role,
				StorageUsed:  int(log.User.StorageUsed),
				StorageQuota: int(log.User.StorageQuota),
				CreatedAt:    log.User.CreatedAt,
			}
		}

		result = append(result, &model.AuditLog{
			ID:           log.ID.String(),
			User:         user,
			Action:       log.Action,
			ResourceType: log.ResourceType,
			ResourceID:   log.ResourceID.String(),
			Details:      &log.Details,
			CreatedAt:    log.CreatedAt,
		})
	}

	return result, nil
}

// ActivityFeed is the resolver for the activityFeed field.
func (r *subscriptionResolver) ActivityFeed(ctx context.Context) (<-chan *model.ActivityEvent, error) {
	// Check authentication (optional - you might want activity feed to be public)
	_, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	
	// Subscribe to activity events
	return realtime.GlobalPublisher.SubscribeToActivity(ctx), nil
}

// Notifications is the resolver for the notifications field.
func (r *subscriptionResolver) Notifications(ctx context.Context, userID string) (<-chan *model.NotificationEvent, error) {
	// Check authentication and authorization
	user, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	
	// Users can only subscribe to their own notifications, or admins can see any
	if user.ID.String() != userID && user.Role != "admin" {
		return nil, fmt.Errorf("ACCESS_DENIED: Can only subscribe to your own notifications")
	}
	
	return realtime.GlobalPublisher.SubscribeToNotifications(ctx, userID), nil
}

// FileUpdates is the resolver for the fileUpdates field.
func (r *subscriptionResolver) FileUpdates(ctx context.Context) (<-chan *model.File, error) {
	// Check authentication
	_, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	
	return realtime.GlobalPublisher.SubscribeToFileUpdates(ctx), nil
}

// FolderUpdates is the resolver for the folderUpdates field.
func (r *subscriptionResolver) FolderUpdates(ctx context.Context) (<-chan *model.Folder, error) {
	// Check authentication
	_, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	
	return realtime.GlobalPublisher.SubscribeToFolderUpdates(ctx), nil
}

// AnalyticsUpdates is the resolver for the analyticsUpdates field.
func (r *subscriptionResolver) AnalyticsUpdates(ctx context.Context) (<-chan *model.AnalyticsSummary, error) {
	// Check if user is admin
	user, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	if user.Role != "admin" {
		return nil, fmt.Errorf("ACCESS_DENIED: Only admins can access analytics updates")
	}
	
	// For now, return a simple channel (can be enhanced later)
	ch := make(chan *model.AnalyticsSummary)
	go func() {
		<-ctx.Done()
		close(ch)
	}()
	return ch, nil
}

// UserActivity is the resolver for the userActivity field.
func (r *subscriptionResolver) UserActivity(ctx context.Context) (<-chan *model.UserActivity, error) {
	// Check if user is admin
	user, err := RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	if user.Role != "admin" {
		return nil, fmt.Errorf("ACCESS_DENIED: Only admins can access user activity updates")
	}
	
	// For now, return a simple channel (can be enhanced later)
	ch := make(chan *model.UserActivity)
	go func() {
		<-ctx.Done()
		close(ch)
	}()
	return ch, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.

func (r *queryResolver) getUploadTrends(days int) ([]*model.UploadTrend, error) {
	var trends []*model.UploadTrend

	// Get upload trends for the last N days
	for i := days - 1; i >= 0; i-- {
		date := time.Now().AddDate(0, 0, -i).Format("2006-01-02")

		var count int64
		var totalSize int64

		startOfDay := time.Now().AddDate(0, 0, -i).Truncate(24 * time.Hour)
		endOfDay := startOfDay.Add(24 * time.Hour)

		r.DB.Model(&db.File{}).Where("created_at >= ? AND created_at < ?", startOfDay, endOfDay).Count(&count)
		r.DB.Model(&db.File{}).Where("created_at >= ? AND created_at < ?", startOfDay, endOfDay).Select("COALESCE(SUM(size), 0)").Scan(&totalSize)

		trends = append(trends, &model.UploadTrend{
			Date:  date,
			Count: int(count),
			Size:  int(totalSize),
		})
	}

	return trends, nil
}
func (r *queryResolver) getUserActivity() ([]*model.UserActivity, error) {
	var activities []*model.UserActivity

	type userStats struct {
		UserID       string
		UserName     string
		UserEmail    string
		FileCount    int64
		TotalSize    int64
		LastActivity *time.Time
		SharingCount int64
	}

	var stats []userStats

	// Get user activity stats
	err := r.DB.Raw(`
		SELECT
			u.id as user_id,
			u.name as user_name,
			u.email as user_email,
			COUNT(DISTINCT f.id) as file_count,
			COALESCE(SUM(f.size), 0) as total_size,
			MAX(f.created_at) as last_activity,
			(SELECT COUNT(*) FROM file_shares fs WHERE fs.user_id = u.id) +
			(SELECT COUNT(*) FROM folder_shares fos WHERE fos.user_id = u.id) as sharing_count
		FROM users u
		LEFT JOIN files f ON f.owner_id = u.id
		GROUP BY u.id, u.name, u.email
		ORDER BY file_count DESC
	`).Scan(&stats).Error

	if err != nil {
		return nil, err
	}

	for _, stat := range stats {
		activities = append(activities, &model.UserActivity{
			UserID:       stat.UserID,
			UserName:     stat.UserName,
			UserEmail:    stat.UserEmail,
			FileCount:    int(stat.FileCount),
			TotalSize:    int(stat.TotalSize),
			LastActivity: stat.LastActivity,
			SharingCount: int(stat.SharingCount),
		})
	}

	return activities, nil
}
func (r *queryResolver) getFileTypeStats() ([]*model.FileTypeStats, error) {
	var stats []*model.FileTypeStats

	type mimeTypeStats struct {
		MimeType  string
		Count     int64
		TotalSize int64
	}

	var mimeStats []mimeTypeStats

	err := r.DB.Model(&db.File{}).
		Select("mime_type, COUNT(*) as count, SUM(size) as total_size").
		Group("mime_type").
		Order("count DESC").
		Scan(&mimeStats).Error

	if err != nil {
		return nil, err
	}

	// Calculate total files for percentage
	var totalFiles int64
	r.DB.Model(&db.File{}).Count(&totalFiles)

	for _, stat := range mimeStats {
		percentage := float64(stat.Count) / float64(totalFiles) * 100
		if totalFiles == 0 {
			percentage = 0
		}

		stats = append(stats, &model.FileTypeStats{
			MimeType:   stat.MimeType,
			Count:      int(stat.Count),
			TotalSize:  int(stat.TotalSize),
			Percentage: percentage,
		})
	}

	return stats, nil
}
func (r *queryResolver) getSharingStats() (*model.SharingStats, error) {
	var totalShares int64
	var publicFiles int64
	var publicFolders int64
	var userShares int64

	// Count sharing stats
	r.DB.Model(&db.FileShare{}).Count(&totalShares)
	r.DB.Model(&db.File{}).Where("is_public = ?", true).Count(&publicFiles)
	r.DB.Model(&db.Folder{}).Where("is_public = ?", true).Count(&publicFolders)

	// User shares = file shares + folder shares
	var folderShares int64
	r.DB.Model(&db.FolderShare{}).Count(&folderShares)
	userShares = totalShares + folderShares

	// Get most shared files
	var mostSharedFiles []*model.File
	var dbFiles []db.File

	err := r.DB.Raw(`
		SELECT f.*, COUNT(fs.id) as share_count
		FROM files f
		LEFT JOIN file_shares fs ON fs.file_id = f.id
		GROUP BY f.id
		ORDER BY share_count DESC, f.download_count DESC
		LIMIT 5
	`).Find(&dbFiles).Error

	if err != nil {
		return nil, err
	}

	for _, file := range dbFiles {
		mostSharedFiles = append(mostSharedFiles, &model.File{
			ID:            file.ID.String(),
			Name:          file.Name,
			ContentHash:   file.ContentHash,
			MimeType:      file.MimeType,
			Size:          int(file.Size),
			IsPublic:      file.IsPublic,
			DownloadCount: int(file.DownloadCount),
			CreatedAt:     file.CreatedAt,
			UpdatedAt:     file.UpdatedAt,
		})
	}

	// Get most shared folders
	var mostSharedFolders []*model.Folder
	var dbFolders []db.Folder

	err = r.DB.Raw(`
		SELECT f.*, COUNT(fs.id) as share_count
		FROM folders f
		LEFT JOIN folder_shares fs ON fs.folder_id = f.id
		GROUP BY f.id
		ORDER BY share_count DESC
		LIMIT 5
	`).Find(&dbFolders).Error

	if err != nil {
		return nil, err
	}

	for _, folder := range dbFolders {
		mostSharedFolders = append(mostSharedFolders, &model.Folder{
			ID:        folder.ID.String(),
			Name:      folder.Name,
			IsPublic:  folder.IsPublic,
			CreatedAt: folder.CreatedAt,
			UpdatedAt: folder.UpdatedAt,
		})
	}

	return &model.SharingStats{
		TotalShares:       int(totalShares),
		PublicFiles:       int(publicFiles),
		PublicFolders:     int(publicFolders),
		UserShares:        int(userShares),
		MostSharedFiles:   mostSharedFiles,
		MostSharedFolders: mostSharedFolders,
	}, nil
}
func (r *mutationResolver) getAllFilesInFolder(tx *gorm.DB, folderId string, files *[]db.File) error {
	// Get direct files in this folder
	var directFiles []db.File
	if err := tx.Where("folder_id = ?", folderId).Find(&directFiles).Error; err != nil {
		return err
	}
	*files = append(*files, directFiles...)

	// Get all subfolders and recurse
	var subfolders []db.Folder
	if err := tx.Where("parent_id = ?", folderId).Find(&subfolders).Error; err != nil {
		return err
	}

	for _, subfolder := range subfolders {
		if err := r.getAllFilesInFolder(tx, subfolder.ID.String(), files); err != nil {
			return err
		}
	}

	return nil
}
func (r *mutationResolver) deleteFileWithDeduplication(tx *gorm.DB, file db.File) error {
	// Get the file content record
	var content db.FileContent
	if err := tx.Where("content_hash = ?", file.ContentHash).First(&content).Error; err != nil {
		return err
	}

	// Delete the file record
	if err := tx.Delete(&file).Error; err != nil {
		return err
	}

	// Decrement reference count
	content.ReferenceCount--
	if content.ReferenceCount <= 0 {
		// No more references, delete the physical file and content record
		if err := r.Storage.DeleteFile(file.ContentHash); err != nil {
			return fmt.Errorf("failed to delete physical file: %w", err)
		}
		if err := tx.Delete(&content).Error; err != nil {
			return fmt.Errorf("failed to delete content record: %w", err)
		}
	} else {
		// Update reference count
		if err := tx.Save(&content).Error; err != nil {
			return err
		}
	}

	return nil
}
